### PR TITLE
feat: completion for % and @

### PR DESCRIPTION
**Pull request by LrWm3**
Adds completion for `@` and `%` symbols.

Tested locally

```
reeldata:~/w/i-devlog $ i 
amend        analyse      digest       find         git          list         mentioned    occurrences  remember     tagged       today        upgrade      yesterday    
reeldata:~/w/i-devlog $ i @
@AdamFiction      @JustinMark  @lrwm3
reeldata:~/w/i-devlog $ i %
%test-project-1  %project-2
```

### CODE REVIEW

**Comment by LrWm3** [comment]
locally i've implemented '@' slightly differently, as I have occurrences like so:

```
30 minutes ago: [repo:i-devlog] (branch:auto-completion) cmsg: 'feat: auto-completion for % and @'
```

which is showing up as a name like so:

`@'`

I am patching it like so for now.
```
words=$(__i_unique_occurrences_completion @ | sed 's/@[^A-Za-z0-9]//g')
```

but I think it might be better to leave without special logic in the completion for now...

**Comment by LrWm3** [comment]
has an issue where complete doesn't work for strings like so `i test @`

edit: resolved

**Comment by kungfusheep** [comment]
This looks awesome! I will merge when I get close to a laptop later today :)

**Comment by kungfusheep** [comment]
all merged! thanks. hope it continues being useful to you

**Pull request merged**
